# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: collision.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'collision.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import object_pb2 as object__pb2
from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x63ollision.proto\x12\x08pisa_api\x1a\x0cobject.proto\x1a\x1cgoogle/protobuf/struct.proto\"\xc8\x01\n\rCollisionInfo\x12\x10\n\x08occurred\x18\x01 \x01(\x08\x12\x0f\n\x07time_ns\x18\x02 \x01(\x03\x12(\n\x07\x61\x63tor_a\x18\x03 \x01(\x0b\x32\x12.pisa_api.ActorRefH\x00\x88\x01\x01\x12(\n\x07\x61\x63tor_b\x18\x04 \x01(\x0b\x32\x12.pisa_api.ActorRefH\x01\x88\x01\x01\x12(\n\x07\x64\x65tails\x18\x05 \x01(\x0b\x32\x17.google.protobuf.StructB\n\n\x08_actor_aB\n\n\x08_actor_bb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'collision_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_COLLISIONINFO']._serialized_start=74
  _globals['_COLLISIONINFO']._serialized_end=274
# @@protoc_insertion_point(module_scope)
