# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: object.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'object.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cobject.proto\x12\x08pisa_api\"\xa1\x01\n\x0fObjectKinematic\x12\x0f\n\x07time_ns\x18\x01 \x01(\x03\x12\t\n\x01x\x18\x02 \x01(\x01\x12\t\n\x01y\x18\x03 \x01(\x01\x12\t\n\x01z\x18\x04 \x01(\x01\x12\x0b\n\x03yaw\x18\x05 \x01(\x01\x12\r\n\x05speed\x18\x06 \x01(\x01\x12\x14\n\x0c\x61\x63\x63\x65leration\x18\x07 \x01(\x01\x12\x10\n\x08yaw_rate\x18\x08 \x01(\x01\x12\x18\n\x10yaw_acceleration\x18\t \x01(\x01\"\xdc\x01\n\x05Shape\x12!\n\x04type\x18\x04 \x01(\x0e\x32\x13.pisa_api.ShapeType\x12-\n\ndimensions\x18\x02 \x01(\x0b\x32\x19.pisa_api.Shape.Dimension\x12(\n\x08vertices\x18\x03 \x03(\x0b\x32\x16.pisa_api.Shape.Vertex\x1a,\n\tDimension\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\x12\t\n\x01z\x18\x03 \x01(\x01\x1a)\n\x06Vertex\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\x12\t\n\x01z\x18\x03 \x01(\x01\"\x92\x01\n\x0bObjectState\x12&\n\x04type\x18\x01 \x01(\x0e\x32\x18.pisa_api.RoadObjectType\x12,\n\tkinematic\x18\x02 \x01(\x0b\x32\x19.pisa_api.ObjectKinematic\x12#\n\x05shape\x18\x03 \x01(\x0b\x32\x0f.pisa_api.ShapeH\x00\x88\x01\x01\x42\x08\n\x06_shape*\xc0\x01\n\x0eRoadObjectType\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x07\n\x03\x43\x41R\x10\x01\x12\t\n\x05TRUCK\x10\x02\x12\x07\n\x03\x42US\x10\x03\x12\x0f\n\x0bSEMITRAILER\x10\x04\x12\x0b\n\x07TRAILER\x10\x05\x12\x0e\n\nMOTORCYCLE\x10\x06\x12\x0b\n\x07\x42ICYCLE\x10\x07\x12\x0e\n\nPEDESTRIAN\x10\x08\x12\x07\n\x03VAN\x10\t\x12\t\n\x05TRAIN\x10\n\x12\x08\n\x04TRAM\x10\x0b\x12\x0f\n\x0bWHEEL_CHAIR\x10\x0c\x12\n\n\x06\x41NIMAL\x10\r*8\n\tShapeType\x12\x10\n\x0c\x42OUNDING_BOX\x10\x00\x12\x0c\n\x08\x43YLINDER\x10\x01\x12\x0b\n\x07POLYGON\x10\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'object_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ROADOBJECTTYPE']._serialized_start=563
  _globals['_ROADOBJECTTYPE']._serialized_end=755
  _globals['_SHAPETYPE']._serialized_start=757
  _globals['_SHAPETYPE']._serialized_end=813
  _globals['_OBJECTKINEMATIC']._serialized_start=27
  _globals['_OBJECTKINEMATIC']._serialized_end=188
  _globals['_SHAPE']._serialized_start=191
  _globals['_SHAPE']._serialized_end=411
  _globals['_SHAPE_DIMENSION']._serialized_start=324
  _globals['_SHAPE_DIMENSION']._serialized_end=368
  _globals['_SHAPE_VERTEX']._serialized_start=370
  _globals['_SHAPE_VERTEX']._serialized_end=411
  _globals['_OBJECTSTATE']._serialized_start=414
  _globals['_OBJECTSTATE']._serialized_end=560
# @@protoc_insertion_point(module_scope)
