# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import empty_pb2 as empty__pb2
from . import pong_pb2 as pong__pb2
from . import sim_server_pb2 as sim__server__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in sim_server_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SimServerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Ping = channel.unary_unary(
                '/pisa_api.SimServer/Ping',
                request_serializer=empty__pb2.Empty.SerializeToString,
                response_deserializer=pong__pb2.Pong.FromString,
                _registered_method=True)
        self.Init = channel.unary_unary(
                '/pisa_api.SimServer/Init',
                request_serializer=sim__server__pb2.SimServerMessages.InitRequest.SerializeToString,
                response_deserializer=sim__server__pb2.SimServerMessages.InitResponse.FromString,
                _registered_method=True)
        self.Reset = channel.unary_unary(
                '/pisa_api.SimServer/Reset',
                request_serializer=sim__server__pb2.SimServerMessages.ResetRequest.SerializeToString,
                response_deserializer=sim__server__pb2.SimServerMessages.ResetResponse.FromString,
                _registered_method=True)
        self.Step = channel.unary_unary(
                '/pisa_api.SimServer/Step',
                request_serializer=sim__server__pb2.SimServerMessages.StepRequest.SerializeToString,
                response_deserializer=sim__server__pb2.SimServerMessages.StepResponse.FromString,
                _registered_method=True)
        self.Stop = channel.unary_unary(
                '/pisa_api.SimServer/Stop',
                request_serializer=empty__pb2.Empty.SerializeToString,
                response_deserializer=empty__pb2.Empty.FromString,
                _registered_method=True)
        self.Close = channel.unary_unary(
                '/pisa_api.SimServer/Close',
                request_serializer=empty__pb2.Empty.SerializeToString,
                response_deserializer=empty__pb2.Empty.FromString,
                _registered_method=True)
        self.ShouldQuit = channel.unary_unary(
                '/pisa_api.SimServer/ShouldQuit',
                request_serializer=empty__pb2.Empty.SerializeToString,
                response_deserializer=sim__server__pb2.SimServerMessages.ShouldQuitResponse.FromString,
                _registered_method=True)


class SimServerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Ping(self, request, context):
        """Check if the server is alive
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Init(self, request, context):
        """Initialize the simulation (e.g., load maps, set weather)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Reset(self, request, context):
        """Reset the simulation with a new scenario
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Step(self, request, context):
        """Advance the simulation by one step with the provided control command
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Stop(self, request, context):
        """Stop the simulation
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Close(self, request, context):
        """Close the simulation server
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ShouldQuit(self, request, context):
        """Check if the simulation should quit
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SimServerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Ping': grpc.unary_unary_rpc_method_handler(
                    servicer.Ping,
                    request_deserializer=empty__pb2.Empty.FromString,
                    response_serializer=pong__pb2.Pong.SerializeToString,
            ),
            'Init': grpc.unary_unary_rpc_method_handler(
                    servicer.Init,
                    request_deserializer=sim__server__pb2.SimServerMessages.InitRequest.FromString,
                    response_serializer=sim__server__pb2.SimServerMessages.InitResponse.SerializeToString,
            ),
            'Reset': grpc.unary_unary_rpc_method_handler(
                    servicer.Reset,
                    request_deserializer=sim__server__pb2.SimServerMessages.ResetRequest.FromString,
                    response_serializer=sim__server__pb2.SimServerMessages.ResetResponse.SerializeToString,
            ),
            'Step': grpc.unary_unary_rpc_method_handler(
                    servicer.Step,
                    request_deserializer=sim__server__pb2.SimServerMessages.StepRequest.FromString,
                    response_serializer=sim__server__pb2.SimServerMessages.StepResponse.SerializeToString,
            ),
            'Stop': grpc.unary_unary_rpc_method_handler(
                    servicer.Stop,
                    request_deserializer=empty__pb2.Empty.FromString,
                    response_serializer=empty__pb2.Empty.SerializeToString,
            ),
            'Close': grpc.unary_unary_rpc_method_handler(
                    servicer.Close,
                    request_deserializer=empty__pb2.Empty.FromString,
                    response_serializer=empty__pb2.Empty.SerializeToString,
            ),
            'ShouldQuit': grpc.unary_unary_rpc_method_handler(
                    servicer.ShouldQuit,
                    request_deserializer=empty__pb2.Empty.FromString,
                    response_serializer=sim__server__pb2.SimServerMessages.ShouldQuitResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'pisa_api.SimServer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('pisa_api.SimServer', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SimServer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Ping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pisa_api.SimServer/Ping',
            empty__pb2.Empty.SerializeToString,
            pong__pb2.Pong.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Init(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pisa_api.SimServer/Init',
            sim__server__pb2.SimServerMessages.InitRequest.SerializeToString,
            sim__server__pb2.SimServerMessages.InitResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Reset(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pisa_api.SimServer/Reset',
            sim__server__pb2.SimServerMessages.ResetRequest.SerializeToString,
            sim__server__pb2.SimServerMessages.ResetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Step(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pisa_api.SimServer/Step',
            sim__server__pb2.SimServerMessages.StepRequest.SerializeToString,
            sim__server__pb2.SimServerMessages.StepResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Stop(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pisa_api.SimServer/Stop',
            empty__pb2.Empty.SerializeToString,
            empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Close(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pisa_api.SimServer/Close',
            empty__pb2.Empty.SerializeToString,
            empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ShouldQuit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pisa_api.SimServer/ShouldQuit',
            empty__pb2.Empty.SerializeToString,
            sim__server__pb2.SimServerMessages.ShouldQuitResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
